"""Agregar campo activo a maestro

Revision ID: 05d482b1aa78
Revises: e96fbb16e83a
Create Date: 2025-10-16 11:15:51.203979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d482b1aa78'
down_revision = 'e96fbb16e83a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
