"""Agregar campo tipo a nominaciones

Revision ID: 490250a4c1e1
Revises: 5cb2a451177f
Create Date: 2025-10-10 13:56:04.509953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490250a4c1e1'
down_revision = '5cb2a451177f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nominaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nominaciones', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
