"""Agrega maestro_nominado_id y permite alumno_id nulo

Revision ID: 5cb2a451177f
Revises: 
Create Date: 2025-10-10 13:38:28.663128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cb2a451177f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumno')
    op.drop_table('valor')
    op.drop_table('ciclo_escolar')
    op.drop_table('playing_with_neon')
    op.drop_table('nominacion')
    op.drop_table('bloque')
    with op.batch_alter_table('nominaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maestro_nominado_id', sa.Integer(), nullable=True))
        batch_op.alter_column('maestro_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('valor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ciclo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'maestros', ['maestro_nominado_id'], ['id'])
        batch_op.drop_column('razon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nominaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razon', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('fecha',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('ciclo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('valor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('maestro_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('maestro_nominado_id')

    op.create_table('bloque',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('bloque_pkey'))
    )
    op.create_table('nominacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('votos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('nominacion_pkey'))
    )
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.create_table('ciclo_escolar',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ciclo_escolar_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_asamblea_1', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_asamblea_2', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_asamblea_3', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_asamblea_4', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ciclo_escolar_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('valor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('valor_pkey'))
    )
    op.create_table('alumno',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('grado', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('grupo', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('nivel', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ciclo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ciclo_id'], ['ciclo_escolar.id'], name=op.f('alumno_ciclo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alumno_pkey'))
    )
    # ### end Alembic commands ###
