"""Aumentar tamaño del campo grupo

Revision ID: 72fea104c4bb
Revises: 05d482b1aa78
Create Date: 2025-10-20 10:44:17.741490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fea104c4bb'
down_revision = '05d482b1aa78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('grupo',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('grupo',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
