"""Agrega campo orden a Bloque

Revision ID: 7314827fe0a5
Revises: 738e08f9e424
Create Date: 2025-10-15 10:05:30.810819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7314827fe0a5'
down_revision = '738e08f9e424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloques', schema=None) as batch_op:
        batch_op.drop_column('orden')

    # ### end Alembic commands ###
