"""Remove bloque_id from Maestro

Revision ID: 738e08f9e424
Revises: cfacc3b7413e
Create Date: 2025-10-14 12:37:41.087377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738e08f9e424'
down_revision = 'cfacc3b7413e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('maestros_bloque_id_fkey'), type_='foreignkey')
        batch_op.drop_column('bloque_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloque_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('maestros_bloque_id_fkey'), 'bloques', ['bloque_id'], ['id'])

    # ### end Alembic commands ###
