"""Add EventoAsamblea, PlantillaInvitacion and email_tutor

Revision ID: 87bd61d1cbf1
Revises: 490250a4c1e1
Create Date: 2025-10-14 11:54:03.783181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bd61d1cbf1'
down_revision = '490250a4c1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_tutor', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('email_tutor')

    # ### end Alembic commands ###
