"""Add bloque_id to Maestro

Revision ID: cfacc3b7413e
Revises: f680d3d89434
Create Date: 2025-10-14 12:30:14.563033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfacc3b7413e'
down_revision = 'f680d3d89434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloque_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bloques', ['bloque_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maestros', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bloque_id')

    # ### end Alembic commands ###
