"""add estado to EventoAsamblea

Revision ID: e96fbb16e83a
Revises: 7314827fe0a5
Create Date: 2025-10-16 09:02:42.276794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96fbb16e83a'
down_revision = '7314827fe0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_asamblea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_asamblea', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
